/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as VesselsRouteImport } from './routes/vessels'
import { Route as BrokerageRouteImport } from './routes/brokerage'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const VesselsRoute = VesselsRouteImport.update({
  id: '/vessels',
  path: '/vessels',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokerageRoute = BrokerageRouteImport.update({
  id: '/brokerage',
  path: '/brokerage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects': typeof ProjectsRoute
  '/about': typeof AboutRoute
  '/services': typeof ServicesRoute
  '/vessels': typeof VesselsRoute
  '/brokerage': typeof BrokerageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects': typeof ProjectsRoute
  '/about': typeof AboutRoute
  '/services': typeof ServicesRoute
  '/vessels': typeof VesselsRoute
  '/brokerage': typeof BrokerageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects': typeof ProjectsRoute
  '/about': typeof AboutRoute
  '/services': typeof ServicesRoute
  '/vessels': typeof VesselsRoute
  '/brokerage': typeof BrokerageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sitemap.xml' | '/projects' | '/about' | '/services' | '/vessels' | '/brokerage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sitemap.xml' | '/projects' | '/about' | '/services' | '/vessels' | '/brokerage'
  id: '__root__' | '/' | '/sitemap.xml' | '/projects' | '/about' | '/services' | '/vessels' | '/brokerage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProjectsRoute: typeof ProjectsRoute
  AboutRoute: typeof AboutRoute
  ServicesRoute: typeof ServicesRoute
  VesselsRoute: typeof VesselsRoute
  BrokerageRoute: typeof BrokerageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vessels': {
      id: '/vessels'
      path: '/vessels'
      fullPath: '/vessels'
      preLoaderRoute: typeof VesselsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokerage': {
      id: '/brokerage'
      path: '/brokerage'
      fullPath: '/brokerage'
      preLoaderRoute: typeof BrokerageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProjectsRoute: ProjectsRoute,
  AboutRoute: AboutRoute,
  ServicesRoute: ServicesRoute,
  VesselsRoute: VesselsRoute,
  BrokerageRoute: BrokerageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
